# Generated by Django 5.1.5 on 2025-01-16 00:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('datainicio', models.DateField()),
                ('datafim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologias',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alocacoes',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('horas', models.TimeField()),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaDev.programador')),
                ('projetos', models.ManyToManyField(to='gerenciaDev.projetos')),
            ],
        ),
        migrations.AddField(
            model_name='projetos',
            name='tecnologias',
            field=models.ManyToManyField(to='gerenciaDev.tecnologias'),
        ),
        migrations.AddField(
            model_name='programador',
            name='tecnologias',
            field=models.ManyToManyField(to='gerenciaDev.tecnologias'),
        ),
    ]
