# Generated by Django 5.1.5 on 2025-01-16 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaDev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacoes',
            name='data_alocacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projetos',
            name='horas',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
