# Generated by Django 5.1.5 on 2025-01-16 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaDev', '0002_alocacoes_data_alocacao_projetos_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alocacoes',
            name='data_alocacao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
